name: kasperaase
favicon: null
layout_spectrum: 1
typography_spectrum: 0.884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e7dd'
    - '#a99d92'
    - '#060916'
    - '#ff00f4'
    - '#7a0092'
  brandStrength: 0.5
  lightness: 0.6119933237787336
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
